### ISSUE TITLE
Merge wiki refactor

### ISSUE THREAD

**Issue by emdashdrupal** [taipei-native/Carto#1]
It seems you can't merge wiki content via pull request, so I'm sending for review and merge: 

[My fork](https://github.com/emdashdrupal/Carto/tree/wiki-updates-emdashdrupal)

Summary of changes: 

- Moved changelog to its own file for easier maintenance.
- Restructured the content so that it's more action-focused.
- Converted long lists of features into tables.
- Editorial changes.
- Added admonitions (note, tip, etc.) which are supported in GitHub pages.

**Comment by taipei-native** [comment]
The changes were reviewed, merged, and pushed (The latest wiki commit was [ee64656](https://github.com/taipei-native/Carto/wiki/_history).) Thanks for your contribution!
